name: Build Docker image
on:
  # schedule:
  #   - cron: '0 0 * * 1,3,6' # @at 0h0m0s every 3 days
  push:
    branches: [main]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      #
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      #
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      #
      - name: Login to DockerHub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        if: env.DOCKERHUB_USERNAME != null
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      #
      - name: Build and push (Ubuntu)
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          context: .
          push: ${{ fromJSON(env.DOCKERHUB_USERNAME != null) }}
          tags: ${{ github.repository }}:latest

      - name: Build and push (Alpine)
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile.alpine
          context: .
          push: ${{ fromJSON(env.DOCKERHUB_USERNAME != null) }}
          tags: ${{ github.repository }}:alpine
